export const API_CONFIG = {
    baseUrl: "http://localhost:4000/api",
    endpoints: {
        articles: "/getarticulos",
        totalCount: "/getTotalArticulos",
        ordenesPendientes: "/inicio/ordenespendientes",
        ventasMes: "/inicio/ventasmes",
        productosInventario: "/inicio/productosinventario",
        ventasMesAnterior: "/inicio/ventasmesanterior",
        ordenesRecientes: "/inicio/ordenesrecientes",
        ventasXCategoria: "/inicio/ventasxcategoria",
        productosMasVendidosMesActual: "/inicio/productosmasvendidosmesactual",
        usuarios: "/gestion/usuarios",
        usuario: "/gestion/usuario/:id",
        crearUsuario: "/gestion/crear-usuario",
        actualizarRolUsuario: "/gestion/actualizar-rol-usuario",
        actualizarNombreUsuario: "/gestion/actualizar-nombre-usuario",
        actualizarEmailUsuario: "/gestion/actualizar-email-usuario",
        eliminarUsuario: "/gestion/eliminar-usuario",
        getAlertas: "/alertas/getAlertas",
        getProveedoresResumen: "/gestion-proveedores/proveedores-resumen",
        getDetalleProveedor: "/gestion-proveedores/detalle-proveedor/:id",
        getTiposProveedores: "/gestion-proveedores/tipos-proveedores",
        getTiposPagosProveedores: "/gestion-proveedores/tipos-pagos-proveedores",
        crearProveedor: "/gestion-proveedores/crear-proveedor",
        actualizarNombreProveedor: "/gestion-proveedores/actualizar-nombre/:id",
        actualizarNombreContactoProveedor: "/gestion-proveedores/actualizar-nombre-contacto/:id",
        actualizarDireccionProveedor: "/gestion-proveedores/actualizar-direccion/:id",
        actualizarEmailProveedor: "/gestion-proveedores/actualizar-email/:id",
        actualizarTelefonoProveedor: "/gestion-proveedores/actualizar-telefono/:id",
        actualizarTipoProveedor: "/gestion-proveedores/actualizar-tipo/:id",
        actualizarTipoPagoProveedor: "/gestion-proveedores/actualizar-tipo-pago/:id",
        getResumenCategorias: "/gestion-proveedores/resumen-categorias",
        getDistribucionProveedorInventario: "/gestion-proveedores/distribucion-proveedor-inventario",
        compras: {
            getData: "/compras/getdata",
            crearOrden: "/compras/crearOrden"
        }
    }
};